remote:
  type: url
  param:
    url: https://config.remoteurl.com/project-name/.env

#remote:
#  type: git
#  param:
#    token: # Your GitHub token
#    owner: # Your GitHub username
#    repo: # Your GitHub repository
#    path: # Your GitHub file path
