remote:
  type: spring
  format: json
  param:
    serverUrl: http://localhost:9078
    applicationName: user-service
    profile: live, stage
  debug: true

#
#remote:
#  type: url
#  param:
#    url: https://jsonplaceholder.typicode.com/todos/1

#remote:
#  type: git
#  param:
#    token: # Your GitHub token
#    owner: # Your GitHub username
#    repo: # Your GitHub repository
#    branch: # Your GitHub branch
#    path: # Your GitHub file path
